// apps/web/src/shared/ui/index.ts
// Public API of the v3 "Bioluminescent Terminal" design-system kit. Modules and
// routes import ONLY from 'shared/ui' — never from the individual component
// files. Component inventory + variants: docs/frontend/design.md §6.
export { AppErrorBoundary } from './AppErrorBoundary'
export { AppShell } from './AppShell'
export type { AppShellProps, AppShellUser } from './AppShell'
export { Badge } from './Badge'
export type { BadgeProps, BadgeVariant } from './Badge'
export { Button } from './Button'
export type { ButtonProps, ButtonSize, ButtonVariant } from './Button'
export { EmptyState } from './EmptyState'
export type { EmptyStateProps } from './EmptyState'
export { ErrorState } from './ErrorState'
export type { ErrorStateProps } from './ErrorState'
export { Input } from './Input'
export type { InputProps } from './Input'
export { Modal } from './Modal'
export type { ModalProps } from './Modal'
export { LangSwitch } from './LangSwitch'
export { NotFoundPage } from './NotFoundPage'
export { OfflineOverlay } from './OfflineOverlay'
export { PillGroup } from './PillGroup'
export type { PillGroupProps, PillOption } from './PillGroup'
export { Progress } from './Progress'
export type { ProgressProps } from './Progress'
export { Select } from './Select'
export type { SelectOption, SelectProps } from './Select'
// Poster art + the palette list so consumers can lay out the whole spread
export { SHOWCASE_PALETTES, ShowcasePoster } from './ShowcasePoster'
export type { ShowcasePalette, ShowcasePosterProps } from './ShowcasePoster'
export { Skeleton } from './Skeleton'
export type { SkeletonProps } from './Skeleton'
