// apps/web/src/main.tsx
// SPA entry: builds the TanStack Router from the generated route tree and mounts React.
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

// Router instance — the route tree is generated by @tanstack/router-plugin from src/routes/
const router = createRouter({ routeTree })

// Register the router type once so every <Link>/navigate call is fully typed.
// (interface is required here: TanStack Router relies on declaration merging.)
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (!rootElement) throw new Error('#root element is missing in index.html')

createRoot(rootElement).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
)
