// apps/web/src/main.tsx
// SPA entry: builds the TanStack Router from the generated route tree and mounts React.
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'
// Self-hosted fonts (design.md v3 "Bioluminescent Terminal"): JetBrains Mono is
// THE typeface (400 + 500, latin AND cyrillic — RU is a first-class locale);
// DM Sans is the sparing secondary body face (latin only — no Cyrillic subset
// exists, RU prose falls back to the system sans by design). Imported BEFORE
// theme.css so the @font-face rules exist when the tokens reference the names.
import '@fontsource/jetbrains-mono/latin-400.css'
import '@fontsource/jetbrains-mono/latin-500.css'
import '@fontsource/jetbrains-mono/cyrillic-400.css'
import '@fontsource/jetbrains-mono/cyrillic-500.css'
import '@fontsource/dm-sans/latin-400.css'
import '@fontsource/dm-sans/latin-500.css'
// Tailwind v4 entry + the v3 terminal @theme tokens — the app's ONLY stylesheet
import 'shared/config/theme.css'

// Router instance — the route tree is generated by @tanstack/router-plugin from src/routes/
const router = createRouter({ routeTree })

// Register the router type once so every <Link>/navigate call is fully typed.
// (interface is required here: TanStack Router relies on declaration merging.)
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (!rootElement) throw new Error('#root element is missing in index.html')

createRoot(rootElement).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
)
