// apps/web/src/main.tsx
// SPA entry: builds the TanStack Router from the generated route tree and mounts React.
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'
// Self-hosted variable fonts (design.md v2): Fraunces = display serif (opsz axis
// for optical sizing, italic for the accent word), Space Grotesk = UI grotesk.
// Imported BEFORE theme.css so the @font-face rules exist when the tokens
// reference the family names.
import '@fontsource-variable/fraunces/opsz.css'
import '@fontsource-variable/fraunces/opsz-italic.css'
// Explicit .css path: the package's bare entry has no type declarations, and
// tsc (TS2882) rejects untyped side-effect imports — vite treats both the same
import '@fontsource-variable/space-grotesk/index.css'
// Tailwind v4 entry + "Light Editorial" @theme tokens — the app's ONLY stylesheet
import 'shared/config/theme.css'

// Router instance — the route tree is generated by @tanstack/router-plugin from src/routes/
const router = createRouter({ routeTree })

// Register the router type once so every <Link>/navigate call is fully typed.
// (interface is required here: TanStack Router relies on declaration merging.)
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (!rootElement) throw new Error('#root element is missing in index.html')

createRoot(rootElement).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
)
