/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellPricingRouteImport } from './routes/_shell.pricing'
import { Route as ShellLibraryRouteImport } from './routes/_shell.library'
import { Route as ShellEntitiesRouteImport } from './routes/_shell.entities'
import { Route as ShellCreateRouteImport } from './routes/_shell.create'
import { Route as ShellTemplatesIndexRouteImport } from './routes/_shell.templates.index'
import { Route as ShellCinemaIndexRouteImport } from './routes/_shell.cinema.index'
import { Route as ShellCinemaFilmIdRouteImport } from './routes/_shell.cinema.$filmId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellPricingRoute = ShellPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEntitiesRoute = ShellEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCreateRoute = ShellCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTemplatesIndexRoute = ShellTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCinemaIndexRoute = ShellCinemaIndexRouteImport.update({
  id: '/cinema/',
  path: '/cinema/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCinemaFilmIdRoute = ShellCinemaFilmIdRouteImport.update({
  id: '/cinema/$filmId',
  path: '/cinema/$filmId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/create': typeof ShellCreateRoute
  '/entities': typeof ShellEntitiesRoute
  '/library': typeof ShellLibraryRoute
  '/pricing': typeof ShellPricingRoute
  '/cinema/$filmId': typeof ShellCinemaFilmIdRoute
  '/cinema/': typeof ShellCinemaIndexRoute
  '/templates/': typeof ShellTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/create': typeof ShellCreateRoute
  '/entities': typeof ShellEntitiesRoute
  '/library': typeof ShellLibraryRoute
  '/pricing': typeof ShellPricingRoute
  '/cinema/$filmId': typeof ShellCinemaFilmIdRoute
  '/cinema': typeof ShellCinemaIndexRoute
  '/templates': typeof ShellTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/create': typeof ShellCreateRoute
  '/_shell/entities': typeof ShellEntitiesRoute
  '/_shell/library': typeof ShellLibraryRoute
  '/_shell/pricing': typeof ShellPricingRoute
  '/_shell/cinema/$filmId': typeof ShellCinemaFilmIdRoute
  '/_shell/cinema/': typeof ShellCinemaIndexRoute
  '/_shell/templates/': typeof ShellTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/create'
    | '/entities'
    | '/library'
    | '/pricing'
    | '/cinema/$filmId'
    | '/cinema/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/create'
    | '/entities'
    | '/library'
    | '/pricing'
    | '/cinema/$filmId'
    | '/cinema'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/create'
    | '/_shell/entities'
    | '/_shell/library'
    | '/_shell/pricing'
    | '/_shell/cinema/$filmId'
    | '/_shell/cinema/'
    | '/_shell/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/pricing': {
      id: '/_shell/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ShellPricingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library': {
      id: '/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ShellLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/entities': {
      id: '/_shell/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof ShellEntitiesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/create': {
      id: '/_shell/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof ShellCreateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/templates/': {
      id: '/_shell/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof ShellTemplatesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cinema/': {
      id: '/_shell/cinema/'
      path: '/cinema'
      fullPath: '/cinema/'
      preLoaderRoute: typeof ShellCinemaIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cinema/$filmId': {
      id: '/_shell/cinema/$filmId'
      path: '/cinema/$filmId'
      fullPath: '/cinema/$filmId'
      preLoaderRoute: typeof ShellCinemaFilmIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCreateRoute: typeof ShellCreateRoute
  ShellEntitiesRoute: typeof ShellEntitiesRoute
  ShellLibraryRoute: typeof ShellLibraryRoute
  ShellPricingRoute: typeof ShellPricingRoute
  ShellCinemaFilmIdRoute: typeof ShellCinemaFilmIdRoute
  ShellCinemaIndexRoute: typeof ShellCinemaIndexRoute
  ShellTemplatesIndexRoute: typeof ShellTemplatesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCreateRoute: ShellCreateRoute,
  ShellEntitiesRoute: ShellEntitiesRoute,
  ShellLibraryRoute: ShellLibraryRoute,
  ShellPricingRoute: ShellPricingRoute,
  ShellCinemaFilmIdRoute: ShellCinemaFilmIdRoute,
  ShellCinemaIndexRoute: ShellCinemaIndexRoute,
  ShellTemplatesIndexRoute: ShellTemplatesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
