// Integration sensor for the render pipeline: spawns the REAL ffmpeg-static
// binary and asserts the filtergraph we build is actually accepted and produces
// a decodable mp4.
//
// Why this exists: render.test.ts checks buildFfmpegArgs as a pure function and
// films-render.test.ts injects a fake runner, so both stayed green while the
// drawtext escaping produced a filtergraph ffmpeg rejects outright. A title with
// an apostrophe broke the graph and every render with a title failed. Only a
// real spawn catches that class of bug, so the escaping and the graph shape are
// pinned here against ffmpeg itself.
import { spawn } from 'node:child_process'
import { existsSync, mkdtempSync, rmSync, statSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import {
  FFMPEG_PATH,
  buildFfmpegArgs,
  resolveFontPath,
  runFfmpeg,
  type RenderPlan,
  type RenderSegment,
} from '../src/modules/films/render'

// A title carrying every filtergraph metacharacter plus a drawtext expansion
// token — the exact shape a user can type into the shot composer.
const NASTY_TITLE = "Scene 1: it's a 'test' \\ 100% [x] a,b;c"

function ff(args: string[]): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(FFMPEG_PATH!, args, { stdio: ['ignore', 'pipe', 'pipe'] })
    let stdout = ''
    let stderr = ''
    child.stdout.on('data', (b: Buffer) => (stdout += b.toString()))
    child.stderr.on('data', (b: Buffer) => (stderr += b.toString()))
    child.on('close', (code) => resolve({ code: code ?? -1, stdout, stderr }))
  })
}

// Decodes the file end-to-end; any corruption or truncation surfaces on stderr.
async function assertDecodes(file: string): Promise<void> {
  expect(existsSync(file)).toBe(true)
  expect(statSync(file).size).toBeGreaterThan(0)
  const probe = await ff(['-v', 'error', '-i', file, '-f', 'null', '-'])
  expect(probe.stderr.trim()).toBe('')
  expect(probe.code).toBe(0)
}

async function durationSec(file: string): Promise<number> {
  const info = await ff(['-i', file])
  const m = /Duration: (\d+):(\d+):([\d.]+)/.exec(info.stderr)
  if (!m) return -1
  return Number(m[1]) * 3600 + Number(m[2]) * 60 + Number(m[3])
}

// Small canvas + low fps: these tests assert graph correctness, not encode quality.
const W = 160
const H = 120
const FPS = 10

const titleSeg = (text: string, over: Partial<RenderSegment> = {}): RenderSegment => ({
  file: null,
  kind: 'title',
  durationSec: 0.6,
  trimStartSec: 0,
  crossfade: false,
  transitionSec: 0,
  title: { text, position: 'center' },
  ...over,
})

const font = resolveFontPath()

describe.skipIf(!FFMPEG_PATH)('render pipeline against the real ffmpeg', () => {
  let dir: string
  const plan = (segments: RenderSegment[], over: Partial<RenderPlan> = {}): RenderPlan => ({
    width: W,
    height: H,
    segments,
    audio: [],
    fontPath: font,
    outputPath: join(dir, 'out.mp4'),
    fps: FPS,
    ...over,
  })

  beforeAll(() => {
    dir = mkdtempSync(join(tmpdir(), 'render-ffmpeg-'))
  })
  afterAll(() => {
    rmSync(dir, { recursive: true, force: true })
  })

  // The regression that shipped: an apostrophe in a title closed the quoted
  // drawtext value, so ffmpeg parsed the rest of the chain as drawtext options
  // and aborted with "Option not found".
  it.skipIf(!font)(
    'accepts a title containing quotes, colons, backslashes and commas',
    async () => {
      const p = plan([titleSeg(NASTY_TITLE)])
      const result = await runFfmpeg(buildFfmpegArgs(p), 600, () => {})
      expect(result).toEqual({ ok: true })
      await assertDecodes(p.outputPath)
    },
    60_000,
  )

  // A title is literal text. With drawtext's default expansion, `%{pts}` would be
  // substituted per frame — so a static title card must produce identical frames.
  it.skipIf(!font)(
    'renders title text literally rather than expanding %{...} tokens',
    async () => {
      const p = plan([titleSeg('%{pts}')])
      const result = await runFfmpeg(buildFfmpegArgs(p), 600, () => {})
      expect(result).toEqual({ ok: true })

      const md5 = await ff(['-i', p.outputPath, '-f', 'framemd5', '-'])
      const hashes = md5.stdout
        .split('\n')
        .filter((l) => l && !l.startsWith('#'))
        .map((l) => l.split(',').pop()!.trim())
      expect(hashes.length).toBeGreaterThan(1)
      expect(new Set(hashes).size).toBe(1)
    },
    60_000,
  )

  it(
    'renders a mixed timeline (video + image + title, crossfade + cut, audio) into a decodable mp4',
    async () => {
      const clip = join(dir, 'clip.mp4')
      const still = join(dir, 'still.png')
      const tone = join(dir, 'tone.m4a')
      // Real source media, generated by ffmpeg so the test stays hermetic.
      await ff(['-y', '-f', 'lavfi', '-i', `testsrc2=size=320x240:rate=${FPS}:duration=3`, '-c:v', 'libx264', '-pix_fmt', 'yuv420p', clip])
      await ff(['-y', '-f', 'lavfi', '-i', 'testsrc2=size=200x200:duration=1', '-frames:v', '1', still])
      await ff(['-y', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=4', '-c:a', 'aac', tone])

      const p = plan(
        [
          { file: clip, kind: 'video', durationSec: 1, trimStartSec: 0.5, crossfade: false, transitionSec: 0, title: font ? { text: NASTY_TITLE, position: 'top' } : null },
          { file: still, kind: 'image', durationSec: 1, trimStartSec: 0, crossfade: true, transitionSec: 0.4, title: null },
          titleSeg('THE END', { durationSec: 1 }),
        ],
        { audio: [{ file: tone, startSec: 0, gainDb: -6 }] },
      )

      const seen: number[] = []
      // 1 + 1 - 0.4 + 1 = 2.6s
      const result = await runFfmpeg(buildFfmpegArgs(p), 2600, (pct) => seen.push(pct))
      expect(result).toEqual({ ok: true })
      await assertDecodes(p.outputPath)

      const info = await ff(['-i', p.outputPath])
      expect(info.stderr).toMatch(/Stream.*Video: h264/)
      expect(info.stderr).toMatch(/Stream.*Audio: aac/)
      expect(await durationSec(p.outputPath)).toBeCloseTo(2.6, 0)
      // -progress is parsed into a percent stream the render row exposes.
      expect(seen.length).toBeGreaterThan(0)
      expect(Math.max(...seen)).toBeLessThanOrEqual(99)
    },
    120_000,
  )

  // Native generation audio (2026-07-15): a clip generated WITH sound must carry
  // its soundtrack into the export — trimmed to the shot's window, delayed to the
  // clip's place on the timeline, mixed with the film's own tracks. Pinned against
  // the real binary because the [i:a] chain is exactly the kind of graph a pure
  // test can bless while ffmpeg rejects it.
  it(
    'carries a native-audio clip soundtrack into the export mix',
    async () => {
      const noisy = join(dir, 'noisy-clip.mp4')
      // A clip WITH an audio track — video and sine muxed together, like a
      // provider delivers when generation audio is on.
      await ff([
        '-y',
        '-f', 'lavfi', '-i', `testsrc2=size=320x240:rate=${FPS}:duration=2`,
        '-f', 'lavfi', '-i', 'sine=frequency=660:duration=2',
        '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest',
        noisy,
      ])

      const p = plan(
        [
          { file: noisy, kind: 'video', durationSec: 1.5, trimStartSec: 0.2, crossfade: false, transitionSec: 0, title: null, nativeAudio: true },
          titleSeg('QUIET END', { durationSec: 0.8 }),
        ],
        { outputPath: join(dir, 'native-audio.mp4') },
      )

      const result = await runFfmpeg(buildFfmpegArgs(p), 2300, () => {})
      expect(result).toEqual({ ok: true })
      await assertDecodes(p.outputPath)

      const info = await ff(['-i', p.outputPath])
      expect(info.stderr).toMatch(/Stream.*Audio: aac/)
      // The film is still picture-length: 1.5 + 0.8 = 2.3s
      expect(await durationSec(p.outputPath)).toBeCloseTo(2.3, 0)
    },
    120_000,
  )

  // The film's length is the timeline, in both directions: a long music bed is
  // capped, and a short voiceover must not truncate the picture.
  it(
    'caps an over-long audio track to the timeline instead of stretching the film',
    async () => {
      const tone = join(dir, 'long-tone.m4a')
      await ff(['-y', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=5', '-c:a', 'aac', tone])
      const p = plan([titleSeg('A', { durationSec: 1 }), titleSeg('B', { durationSec: 1 })], {
        audio: [{ file: tone, startSec: 0, gainDb: 0 }],
        outputPath: join(dir, 'long-audio.mp4'),
      })
      expect(await runFfmpeg(buildFfmpegArgs(p), 2000, () => {})).toEqual({ ok: true })
      await assertDecodes(p.outputPath)
      expect(await durationSec(p.outputPath)).toBeCloseTo(2, 0)
    },
    120_000,
  )

  it(
    'keeps the full picture when the audio track is shorter than the timeline',
    async () => {
      const tone = join(dir, 'short-tone.m4a')
      await ff(['-y', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=0.5', '-c:a', 'aac', tone])
      const p = plan([titleSeg('A', { durationSec: 1.5 }), titleSeg('B', { durationSec: 1.5 })], {
        audio: [{ file: tone, startSec: 0, gainDb: 0 }],
        outputPath: join(dir, 'short-audio.mp4'),
      })
      expect(await runFfmpeg(buildFfmpegArgs(p), 3000, () => {})).toEqual({ ok: true })
      await assertDecodes(p.outputPath)
      expect(await durationSec(p.outputPath)).toBeCloseTo(3, 0)
    },
    120_000,
  )

  it(
    'fails cleanly with a message when an input file does not exist',
    async () => {
      const p = plan([{ file: join(dir, 'missing.mp4'), kind: 'video', durationSec: 1, trimStartSec: 0, crossfade: false, transitionSec: 0, title: null }])
      const result = await runFfmpeg(buildFfmpegArgs(p), 1000, () => {})
      expect(result.ok).toBe(false)
      if (!result.ok) expect(result.error).not.toBe('')
    },
    60_000,
  )
})
